from __future__ import annotations

from uuid import UUID

from pydantic.v1 import Field

from opensemantic.core.v1 import (
    Enumeration,
    Item,
    OntologyRelated,
)
from opensemantic.v1 import OswBaseModel

# generated by datamodel-codegen:
#   filename:  UnitPrefix.json


class UnitPrefix(Enumeration, OntologyRelated):
    """
    Prefix for unit symbols, e.g. kilo (k), milli (m). See https://si-digital-framework.org/SI/prefixes?lang=en
    """

    class Config:
        schema_extra = {
            "title": "UnitPrefix",
            "@context": [
                "/wiki/Category:OSWd02741381aaa4709ae0753a0edc341ce?action=raw&slot=jsonschema",
                "/wiki/Category:OSW6ef70c808fb54abbbacb059c285713d4?action=raw&slot=jsonschema",
                {"symbol": "Property:HasSymbol", "factor": "Property:HasFactor"},
            ],
            "uuid": "99e0f46a-40ca-4129-a420-b4bb89c4cc45",
            "title*": {"en": "Unit prefix", "de": "Einheitenpräfix"},
            "description": "Prefix for unit symbols, e.g. kilo (k), milli (m). See https://si-digital-framework.org/SI/prefixes?lang=en",
            "description*": {
                "en": "Prefix for unit symbols, e.g. kilo (k), milli (m). See https://si-digital-framework.org/SI/prefixes?lang=en",
                "de": "Vorsilben für Einheiten-Symbole, z.B. kilo (k), milli (m). Siehe https://si-digital-framework.org/SI/prefixes?lang=en",
            },
        }

    type: list[str] | None = ["Category:OSW99e0f46a40ca4129a420b4bb89c4cc45"]
    name: str = Field(..., options={"hidden": False})
    symbol: str = Field(..., title="Symbol")
    """
    e.g. m for milli
    """
    factor: float = Field(..., title="Factor")
    """
    e.g. 1e-3 for milli
    """


# generated by datamodel-codegen:
#   filename:  QuantityUnit.json


class QuantityUnitFactor(OswBaseModel):
    class Config:
        schema_extra = {
            "title": "QuantityUnitFactor",
            "title*": {"en": "Factor", "de": "Faktor"},
        }

    uuid: UUID | None = Field(None, options={"hidden": True}, title="UUID")
    unit: QuantityUnit | None = Field(
        None,
        range="Category:OSWd2520fa016844e01af0097a85bb25b25",
        title="Unit",
        x_oold_required_iri=True,
    )
    exponent: int = Field(..., title="Exponent")


class PrefixUnit(OntologyRelated):
    class Config:
        schema_extra = {
            "_format": "grid-strict",
            "headerTemplate": "{{ self.main_symbol }}",
            "defaultProperties": ["exact_ontology_match", "conversion_factor_from_si"],
        }

    type: list[str] | None = ["Category:OSWd2520fa016844e01af0097a85bb25b25"]
    uuid: str = Field(
        ...,
        dynamic_template="{{_uuid_}}",
        field_comment="format uuid field are copied, if not set in copy_ignore",
        field_format="uuid",
        field_template="dynamic_template",
        options={"hidden": True, "dynamic_template": {"override": "empty"}},
        title="UUID",
    )
    osw_id: str = Field(
        ...,
        dynamic_template="{{_current_subject_}}#OSW{{#replace '-' ''}}{{_own_uuid}}{{/replace}}",
        field_format="dynamic_template",
        options={"hidden": True, "dynamic_template": {"override": "empty"}},
        title="OSW-ID",
        watch={"_own_uuid": "prefix_unit.uuid"},
    )
    conversion_factor_to_main_unit: float = Field(
        ...,
        description_={
            "de": "Die entsprechende Haupteinheit muss mit diesem Faktor multipliziert werden, um diese Einheit zu erhalten."
        },
        title="Conversion Factor (Main Unit)",
        title_={"de": "Umrechnungsfaktor (Haupteinheit)"},
    )
    """
    The corresponding main unit has to be multiplied with this factor to yield this unit
    """
    conversion_factor_from_si: float | None = Field(
        None,
        description_={
            "de": "Die entsprechende SI Einheit muss mit diesem Faktor multipliziert werden, um diese Einheit zu erhalten."
        },
        title="Conversion Factor (SI)",
        title_={"de": "Umrechnungsfaktor (SI)"},
    )
    """
    The corresponding SI unit has to be multiplied with this factor to yield this unit
    """
    prefix: UnitPrefix | None = Field(
        None,
        field_comment="We have to watch the target editor (fieldmap.target_path)",
        options={
            "autocomplete": {
                "query": "[[Category:OSW99e0f46a40ca4129a420b4bb89c4cc45]]|?HasName=name|?HasSymbol=symbol",
                "field_maps": [
                    {
                        "source_path": "$",
                        "template": "{{{result.printouts.symbol.[0]}}}",
                        "target_path": "$(prefix_symbol_)",
                    }
                ],
            },
            "grid_columns": 8,
        },
        range="Category:OSW99e0f46a40ca4129a420b4bb89c4cc45",
        watch={"prefix_symbol_": "prefix_unit.prefix_symbol"},
        x_oold_required_iri=True,
    )
    prefix_symbol: str = Field(..., options={"hidden": True})
    main_symbol: str = Field(
        ...,
        options={"grid_columns": 4},
        template="{{{prefix_symbol_}}}{{{unit_main_symbol_}}}",
        watch={
            "unit_main_symbol_": "root.main_symbol",
            "prefix_symbol_": "prefix_unit.prefix_symbol",
            "prefix_": "prefix_unit.prefix",
        },
    )
    ucum_codes: list[str] | None = Field(
        None,
        description_={
            "de": "Codierung gemäß Unified Code for Units of Measure (UCUM): https://ucum.org/ucum"
        },
        title="UCUM Codes",
        title_={"de": "UCUM Codes"},
    )
    """
    Encoding according to the Unified Code for Units of Measure (UCUM): https://ucum.org/ucum
    """
    system_of_quantities_and_units: list[SystemOfQuantitiesAndUnits] | None = Field(
        None,
        range="Category:OSW27782669526d4d9a8de83659c03c64d5",
        title="System(s) of quantities and units",
    )
    """
    System(s) of quantities and units this unit is applicable in
    """


class ComposedUnitFactor(OswBaseModel):
    class Config:
        schema_extra = {
            "title": "ComposedUnitFactor",
            "title*": {"en": "Factor", "de": "Faktor"},
        }

    uuid: UUID | None = Field(None, options={"hidden": True}, title="UUID")
    unit: QuantityUnit | None = Field(
        None,
        options={
            "autocomplete": {
                "$comment": "Unit or prefixed unit",
                "query": "[[Category:OSWd2520fa016844e01af0097a85bb25b25]][[HasSymbol::like:*{{_user_input}}*]]OR[[-HasPrefixUnit.HasType::Category:OSWd2520fa016844e01af0097a85bb25b25]][[HasSymbol::like:*{{_user_input}}*]]|?HasSymbol=label",
            }
        },
        range="Category:OSWd2520fa016844e01af0097a85bb25b25",
        title="Unit",
        x_oold_required_iri=True,
    )
    exponent: int = Field(..., title="Exponent")


class ComposedUnit(Item, OntologyRelated):
    class Config:
        schema_extra = {
            "_format": "grid-strict",
            "headerTemplate": "{{ self.main_symbol }}",
            "defaultProperties": [
                "conversion_factor_from_si",
                "exact_ontology_match",
                "factor_units",
            ],
        }

    type: list[str] | None = ["Category:OSW6c2aea028a8647cd97f5d7c65c09cd44"]
    uuid: str = Field(
        ...,
        dynamic_template="{{_uuid_}}",
        field_comment="format uuid field are copied, if not set in copy_ignore",
        field_format="uuid",
        field_template="dynamic_template",
        options={"hidden": True, "dynamic_template": {"override": "empty"}},
        title="UUID",
    )
    main_symbol: str = Field(..., options={"grid_columns": 4})
    conversion_factor_from_si: float | None = Field(
        None,
        description_={
            "de": "Die entsprechende SI Einheit muss mit diesem Faktor multipliziert werden, um diese Einheit zu erhalten."
        },
        title="Conversion Factor",
        title_={"de": "Umrechnungsfaktor"},
    )
    """
    The corresponding SI unit has to be multiplied with this factor to yield this unit
    """
    ucum_codes: list[str] | None = Field(
        None,
        description_={
            "de": "Codierung gemäß Unified Code for Units of Measure (UCUM): https://ucum.org/ucum"
        },
        title="UCUM Codes",
        title_={"de": "UCUM Codes"},
    )
    """
    Encoding according to the Unified Code for Units of Measure (UCUM): https://ucum.org/ucum
    """
    factor_units: list[ComposedUnitFactor] | None = Field(
        None,
        eval_template=[
            {
                "type": "mustache-wikitext",
                "value": "{{=<% %>=}} <%#factor_units%> {{Viewer/Link |page=<%unit%>}}^<%exponent%><br> <%/factor_units%>",
                "mode": "render",
            }
        ],
        title="Factor units",
    )
    """
    Unit factors that assemble this composed unit
    """
    system_of_quantities_and_units: list[SystemOfQuantitiesAndUnits] | None = Field(
        None,
        range="Category:OSW27782669526d4d9a8de83659c03c64d5",
        title="System(s) of quantities and units",
    )
    """
    System(s) of quantities and units this unit is applicable in
    """
    composed_units: list["ComposedUnitElement"] | None = Field(
        None,
        _format="table",
        eval_template=[
            {
                "type": "mustache-wikitext",
                "value": "{{=<% %>=}} <%#composed_units%> {{Viewer/Link |page=<%osw_id%>}}<br> <%/composed_units%>",
                "mode": "render",
            }
        ],
        title="ComposedUnitElements",
        title_={"en": "Composed Units", "de": "Zusammengesetzte Einheiten"},
    )
    """
    Variants of prefixed unit components
    """


class QuantityUnit(Item, OntologyRelated):
    """
    Unit for a physical, technical or economical quantity
    """

    class Config:
        schema_extra = {
            "@context": [
                "/wiki/Category:Item?action=raw&slot=jsonschema",
                "/wiki/Category:OSW6ef70c808fb54abbbacb059c285713d4?action=raw&slot=jsonschema",
                {
                    "qudt": "http://qudt.org/schema/qudt/",
                    "composed_units": "Property:HasComposedUnit",
                    "conversion_factor_from_si": "Property:HasConversionFactorFromSI",
                    "factor_units": {
                        "@id": "qudt:hasFactorUnit",
                        "@type": "@id",
                        "@context": {
                            "unit": "qudt:hasUnit",
                            "exponent": "qudt:exponent",
                        },
                    },
                    "factor_units*": {
                        "@id": "Property:HasPart",
                        "@type": "@id",
                        "@context": {
                            "unit*": "Property:HasUnit",
                            "exponent*": "Property:HasExponent",
                        },
                    },
                    "factor_unit_scalar": "qudt:factorUnitScalar",
                    "factor_unit_scalar*": "Property:HasFactorUnitScalar",
                    "prefix_units": "Property:HasPrefixUnit",
                    "prefix": "Property:HasPrefix",
                    "main_symbol": "Property:HasSymbol",
                    "main_symbol*": "Property:Display_title_of",
                    "system_of_quantities_and_units": {
                        "@id": "Property:IsApplicableIn",
                        "@type": "@id",
                    },
                },
            ],
            "uuid": "d2520fa0-1684-4e01-af00-97a85bb25b25",
            "title": "QuantityUnit",
            "title*": {"en": "QuantityUnit"},
            "description": "Unit for a physical, technical or economical quantity",
            "description*": {
                "en": "Unit for a physical, technical or economical quantity"
            },
            "defaultProperties": [
                "composed_units",
                "conversion_factor_from_si",
                "exact_ontology_match",
                "factor_units",
                "prefix_units",
            ],
        }

    type: list[str] | None = ["Category:OSWd2520fa016844e01af0097a85bb25b25"]
    main_symbol: str
    conversion_factor_from_si: float | None = Field(
        None,
        description_={
            "de": "Die entsprechende SI Einheit muss mit diesem Faktor multipliziert werden, um diese Einheit zu erhalten."
        },
        title="Conversion Factor",
        title_={"de": "Umrechnungsfaktor"},
    )
    """
    The corresponding SI unit has to be multiplied with this factor to yield this unit
    """
    ucum_codes: list[str] | None = Field(
        None,
        description_={
            "de": "Codierung gemäß Unified Code for Units of Measure (UCUM): https://ucum.org/ucum"
        },
        title="UCUM Codes",
        title_={"de": "UCUM Codes"},
    )
    """
    Encoding according to the Unified Code for Units of Measure (UCUM): https://ucum.org/ucum
    """
    factor_unit_scalar: float | None = Field(1, title="Factor unit scalar")
    """
    Scalar factor for the factor units. Usually valued one. Example case: Oz 0.0625. This property is only relevant if factor_units are stated.
    """
    factor_units: list[QuantityUnitFactor] | None = Field(
        None,
        eval_template=[
            {
                "type": "mustache-wikitext",
                "value": "{{=<% %>=}} <%#factor_units%> {{Viewer/Link |page=<%unit%>}}^<%exponent%><br> <%/factor_units%>",
                "mode": "render",
            }
        ],
        title="Factor units",
    )
    """
    Unit factors that assemble this composed unit
    """
    prefix_units: list[PrefixUnit] | None = Field(
        None,
        eval_template=[
            {
                "type": "mustache-wikitext",
                "value": "{{=<% %>=}} <%#prefix_units%> {{Viewer/Link |page=<%osw_id%>}}<br> <%/prefix_units%>",
                "mode": "render",
            }
        ],
        field_format="table",
        title="Prefix units",
    )
    """
    Combines a quantity unit with an unit prefix
    """
    composed_units: list[ComposedUnit] | None = Field(
        None,
        eval_template=[
            {
                "type": "mustache-wikitext",
                "value": "{{=<% %>=}} <%#composed_units%> {{Viewer/Link |page=<%osw_id%>}}<br> <%/composed_units%>",
                "mode": "render",
            }
        ],
        field_format="table",
        title="Composed units",
    )
    """
    Variants of prefixed unit components
    """
    system_of_quantities_and_units: list[SystemOfQuantitiesAndUnits] | None = Field(
        None,
        range="Category:OSW27782669526d4d9a8de83659c03c64d5",
        title="System(s) of quantities and units",
    )
    """
    System(s) of quantities and units this unit is applicable in
    """


class SystemOfQuantitiesAndUnits(Item, OntologyRelated):
    class Config:
        schema_extra = {
            "@context": [
                {"qudt": "http://qudt.org/schema/qudt/"},
                "/wiki/Category:Item?action=raw&slot=jsonschema",
                "/wiki/Category:OSW6ef70c808fb54abbbacb059c285713d4?action=raw&slot=jsonschema",
            ],
            "uuid": "27782669-526d-4d9a-8de8-3659c03c64d5",
            "title": "SystemOfQuantitiesAndUnits",
            "title*": {
                "en": "System Of Quantities And Units",
                "de": "System von Größen und Einheiten",
            },
            "description": "",
            "description*": {},
        }

    type: list[str] | None = ["Category:OSW27782669526d4d9a8de83659c03c64d5"]


# generated by datamodel-codegen:
#   filename:  OSW6c2aea028a8647cd97f5d7c65c09cd44.json


class FactorUnit(OswBaseModel):
    class Config:
        schema_extra = {
            "title": "FactorUnit",
            "title*": {"en": "Factor", "de": "Faktor"},
        }

    uuid: str = Field(
        ...,
        dynamic_template="{{_uuid_}}",
        field_comment="format uuid field are copied, if not set in copy_ignore",
        field_format="uuid",
        field_template="dynamic_template",
        options={"hidden": True, "dynamic_template": {"override": "empty"}},
        title="UUID",
    )
    unit: QuantityUnit | None = Field(
        None,
        range="Category:OSWd2520fa016844e01af0097a85bb25b25",
        title="Unit",
        x_oold_required_iri=True,
    )
    exponent: int = Field(..., title="Exponent")


class ComposedFactorUnit(OswBaseModel):
    class Config:
        schema_extra = {
            "title": "ComposedFactorUnit",
            "title*": {"en": "Factor", "de": "Faktor"},
        }

    uuid: str = Field(
        ...,
        dynamic_template="{{_uuid_}}",
        field_comment="format uuid field are copied, if not set in copy_ignore",
        field_format="uuid",
        field_template="dynamic_template",
        options={"hidden": True, "dynamic_template": {"override": "empty"}},
        title="UUID",
    )
    unit: QuantityUnit | None = Field(
        None,
        options={
            "autocomplete": {
                "$comment": "Unit or prefixed unit",
                "query": "[[Category:OSWd2520fa016844e01af0097a85bb25b25]][[HasSymbol::like:*{{_user_input}}*]]OR[[-HasPrefixUnit.HasType::Category:OSWd2520fa016844e01af0097a85bb25b25]][[HasSymbol::like:*{{_user_input}}*]]|?HasSymbol=label",
            }
        },
        range="Category:OSWd2520fa016844e01af0097a85bb25b25",
        title="Unit",
        x_oold_required_iri=True,
    )
    exponent: int = Field(..., title="Exponent")


class ComposedUnitElement(OntologyRelated):
    class Config:
        schema_extra = {
            "title": "ComposedUnitElement",
            "title*": {"en": "Composed Unit", "de": "Zusammengesetzte Einheit"},
            "_format": "grid-strict",
            "headerTemplate": "{{ self.main_symbol }}",
            "defaultProperties": ["exact_ontology_match"],
        }

    uuid: str = Field(
        ...,
        dynamic_template="{{_uuid_}}",
        field_comment="format uuid field are copied, if not set in copy_ignore",
        field_format="uuid",
        field_template="dynamic_template",
        options={"hidden": True, "dynamic_template": {"override": "empty"}},
        title="UUID",
    )
    osw_id: str = Field(
        ...,
        dynamic_template="{{_current_subject_}}#OSW{{#replace '-' ''}}{{_own_uuid}}{{/replace}}",
        field_format="dynamic_template",
        options={"hidden": True, "dynamic_template": {"override": "empty"}},
        title="OSW-ID",
        watch={"_own_uuid": "composed_unit.uuid"},
    )
    conversion_factor_from_si: float | None = Field(
        None,
        Title_={"de": "Umrechnungsfaktor"},
        description_={
            "de": "Die entsprechende SI Einheit muss mit diesem Faktor multipliziert werden, um diese Einheit zu erhalten."
        },
        title="Conversion Factor",
    )
    main_symbol: str = Field(..., options={"grid_columns": 4})
    """
    The corresponding SI unit has to be multiplied with this factor to yield this unit
    """
    ucum_codes: list[str] | None = Field(
        None,
        description_={
            "de": "Codierung gemäß Unified Code for Units of Measure (UCUM): https://ucum.org/ucum"
        },
        title="UCUM Codes",
        title_={"de": "UCUM Codes"},
    )
    """
    Encoding according to the Unified Code for Units of Measure (UCUM): https://ucum.org/ucum
    """
    factor_units: list[ComposedFactorUnit] = Field(
        ...,
        eval_template=[
            {
                "type": "mustache-wikitext",
                "value": "{{=<% %>=}} <%#factor_units%> {{Viewer/Link |page=<%unit%>}}^<%exponent%><br> <%/factor_units%>",
                "mode": "render",
            }
        ],
        min_items=1,
        title="ComposedFactorUnits",
        title_={"en": "Factor units", "de": "Einheiten-Faktoren"},
    )
    """
    Unit factors that assemble this composed unit
    """
    system_of_quantities_and_units: list[SystemOfQuantitiesAndUnits] | None = Field(
        None,
        range="Category:OSW27782669526d4d9a8de83659c03c64d5",
        title="System(s) of quantities and units",
    )
    """
    System(s) of quantities and units this unit is applicable in
    """


# generated by datamodel-codegen:
#   filename:  QuantityKind.json


class QuantityKind(Item, OntologyRelated):
    """
    Physical, technical or economical quantities
    """

    class Config:
        schema_extra = {
            "@context": [
                "/wiki/Category:Item?action=raw&slot=jsonschema",
                "/wiki/Category:OSW6ef70c808fb54abbbacb059c285713d4?action=raw&slot=jsonschema",
                {"units": {"@type": "@id", "@id": "Property:HasUnit"}},
            ],
            "uuid": "00fbd6fe-ecb5-4089-97ca-18d4e681a131",
            "title": "QuantityKind",
            "title*": {"en": "Quantity Kind"},
            "description": "Physical, technical or economical quantities",
            "description*": {"en": "Physical, technical or economical quantities"},
            "defaultProperties": ["exact_ontology_match", "units"],
        }

    type: list[str] | None = ["Category:OSW00fbd6feecb5408997ca18d4e681a131"]
    units: list[QuantityUnit] | None = Field(
        None, range="Category:OSWd2520fa016844e01af0097a85bb25b25"
    )


# generated by datamodel-codegen:
#   filename:  SystemOfQuantitiesAndUnits.json


ComposedFactorUnit.update_forward_refs()
ComposedUnit.update_forward_refs()
ComposedUnitElement.update_forward_refs()
ComposedUnitFactor.update_forward_refs()
FactorUnit.update_forward_refs()
PrefixUnit.update_forward_refs()
QuantityKind.update_forward_refs()
QuantityUnit.update_forward_refs()
QuantityUnitFactor.update_forward_refs()
SystemOfQuantitiesAndUnits.update_forward_refs()
UnitPrefix.update_forward_refs()
